disabled_rules:
  - identifier_name
  - force_cast
  - line_length
  - force_try
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - type_body_length

opt_in_rules:
  - indentation_width

indentation_width:
  indentation_width: 2
