name: CI

on: [push, pull_request]

jobs:
  test_lint:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run:  ./Scripts/setup.sh
        env:
          APP_IDENTIFIER: org.blackcandy
      - name: Test and Lint
        run: |
          swiftlint
          set -o pipefail && xcodebuild test -scheme "BlackCandy" -destination platform="iOS Simulator,name=iPhone 15 Pro Max,OS=17.2" | xcpretty --test
