name: CI

on: [push, pull_request]

jobs:
  test_lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test and Lint
        run: |
          swiftlint
          xcodebuild test -scheme "BlackCandy" -destination platform="iOS Simulator,name=iPhone 14 Pro Max,OS=16.1"
